<?php require('template/header.phtml');?>
<script>
    function signIn(event) {
        fetch('Models/Scripts/signIn.php?q=' + "<?php echo $_SESSION['ajaxToken'];?>" + "ʌ" + document.getElementById("username").value + "ʌ" + document.getElementById("password").value).then(function (response) {
            return response.text();
        }).then(function (data) {
            if(data === 'success') {
                window.location.replace("/index.php");
            }
            else{
                response(data);
            }
        }).catch(function (error) {
            console.log('Error: ' + error);
        });
    }
    function response(data){
        const node = document.createTextNode(data);
        para = document.createElement('p'); // create p tag
        para.className = "error";
        para.appendChild(node);
        const element = document.getElementById('error'); // get location of div tag
        element.innerHTML = ''; // clear any error message already in place
        element.appendChild(para); // display message
    }
</script>
<div id="error">

</div>
    <form>
        <div>
            <label>Username:</label>
            <input id="username" required="required" class="form-control" type="text" placeholder="user name" value="">
        </div>
        <div>
            <label>Password:</label>
            <input id="password" required="required" class="form-control" type="password" placeholder="password" value="">
        </div>
        <p></p>
        <div>
            <button type="button" id="sign-in" class="btn btn-primary btn-block">Load More</button>
        </div>
    </form>
    <script>
        document.getElementById('sign-in').addEventListener('click', signIn, false);
    </script>
<?php require('template/footer.phtml');?>